<a href="https://colab.research.google.com/github/ram-elgov/IntroToML/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Visualizing the Hoeffding bound (10 pts).

## imports

In [ ]:
import numpy as np
import numpy.random
from sklearn.datasets import fetch_openml

## constants

In [ ]:
N = 200000
n = 20
p = 0.5

## generate Nxn matrix

In [ ]:
samples = np.random.binomial(1, p, size=(N,n))

In [ ]:
print(samples)

[[1 1 1 ... 0 1 0]
 [1 0 0 ... 0 1 1]
 [0 1 1 ... 0 1 1]
 ...
 [0 1 1 ... 0 1 0]
 [1 0 1 ... 1 1 1]
 [1 1 0 ... 0 0 0]]


In [ ]:
row_mean = np.mean(samples, axis=1)

In [ ]:
print(row_mean)

[0.5  0.65 0.7  ... 0.6  0.6  0.4 ]


In [ ]:
epsilons = np.linspace(0,1,50)
print(epsilons)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [ ]:
empirical_probability = []
for epsilon in epsilons:
  f = lambda x : 1 if abs(x - p) > epsilon else 0
  f_v = np.vectorize(f)
  empirical_probability.append(np.sum(f_v(row_mean)) / N)
print(empirical_probability)

[0.824745, 0.824745, 0.824745, 0.503835, 0.503835, 0.264895, 0.264895, 0.264895, 0.11668, 0.11668, 0.041985, 0.041985, 0.041985, 0.01208, 0.01208, 0.00257, 0.00257, 0.00257, 0.000335, 0.000335, 5e-05, 5e-05, 5e-05, 5e-06, 5e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [ ]:
mnist = fetch_openml('mnist_784', as_frame=False)
data = mnist['data']
labels = mnist['target']

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
idx = numpy.random.RandomState(0).choice(70000, 11000)
train = data[idx[:10000], :].astype(int)
train_labels = labels[idx[:10000]]
test = data[idx[10000:], :].astype(int)
test_labels = labels[idx[10000:]]